# Generated by Django 2.1.1 on 2018-10-25 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling', '0018_auto_20180920_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='first_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to=settings.AUTH_USER_MODEL, verbose_name='First User'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='second_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to=settings.AUTH_USER_MODEL, verbose_name='Second User'),
        ),
    ]
